### ISSUE TITLE
Polybase launch mainnet

### ISSUE THREAD

**Issue by xinaxu** [data-preservation-programs/RepPoly#14]
ETA: 2023-09-01
```[tasklist]
### Tasks
- [ ] https://github.com/data-preservation-programs/RepPoly/pull/31
- [ ] https://github.com/data-preservation-programs/RepPoly/pull/34
- [ ] https://github.com/data-preservation-programs/RepPoly/pull/6
```

**Comment by stephen-pl** [comment]
Im going to assume this happens after the hackathon?

**Comment by stephen-pl** [comment]
Sounds good. Once I get the error not found issue resolved ill fill all the data in a new schema, get sign off and then we can try launching on mainnet :)
