### ISSUE TITLE
[EPIC] Ship Polybase

### ISSUE THREAD

**Issue by xmcai2016** [data-preservation-programs/RepPoly#15]
```[tasklist]
### dev tasks
- [ ] https://github.com/data-preservation-programs/RepPoly/issues/14
- [ ] https://github.com/data-preservation-programs/RepPoly/issues/13
```

```[tasklist]
### PM Tasks
- [ ] https://github.com/data-preservation-programs/RepPoly/issues/16
```
ETA: 2023-10-01
